import turtle
turtle.shape("turtle")
turtle.left(120)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.up()
turtle.backward(50)
turtle.down()
turtle.left(120)
turtle.forward(50)
turtle.up()
turtle.right(60)
turtle.forward(50)

turtle.left(60)
turtle.forward(30)
turtle.left(90)
turtle.down()
turtle.forward(80)
turtle.up()
turtle.backward(40)
turtle.right(90)
turtle.down()
turtle.forward(50)
turtle.left(90)
turtle.forward(40)
turtle.backward(80)
turtle.right(90)
turtle.up()
turtle.forward(30)
turtle.down()
for x in range(2):
	turtle.rt(70)
	turtle.forward(90)

turtle.exitonclick()
